### ISSUE TITLE
Email count isn't visible anymore...last unread email overlaps it.

### ISSUE THREAD

**Issue by InFuz** [georgyangelov/gmail-speeddial-opera-next#2]
For a long time there is a problem with styles. I corrected it and sent pull request. You couldn't update extension?

**Comment by georgyangelov** [comment]
Will update it now. Thank you for this! :)

**Comment by InFuz** [comment]
Will the extension be updated? At addons.opera.com

**Comment by georgyangelov** [comment]
I've put it for update, but they need to review it.

**Comment by InFuz** [comment]
Ok. How long does it usually take?)

**Comment by georgyangelov** [comment]
I think they released it a few hours ago. Try to update manually.

**Comment by InFuz** [comment]
Yes. Just now updated. A couple of hours ago there was an old version.
